In [2]:
import pandas as pd

train_df = pd.read_parquet("../data/processed/train.parquet")
valid_df = pd.read_parquet("../data/processed/valid.parquet")
test_df = pd.read_parquet("../data/processed/test.parquet")
train_preimputed_df = pd.read_parquet("../data/processed/train_pre_impute.parquet")

In [4]:
train_df.head()

,Age,Year_of_Study,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,Sleep_Hours,Screen_Time_Hours,Exercise_Freq_Per_Week,Social_Activity_Score,...,Department_Medicine,Department_Science,Department_Unknown,Residence_Type_Day Scholar,Residence_Type_Hostel,Residence_Type_PG/Rented,Residence_Type_Unknown,Part_Time_Job_No,Part_Time_Job_Unknown,Part_Time_Job_Yes
0,-1.542723,-1.163245,-0.622722,-0.024165,-0.321975,0.151377,0.958684,0.296026,-0.019921,-0.929854,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.001379,1.566157,-2.030806,-0.870306,-0.574747,0.151377,-0.533896,1.100858,-0.019921,1.318193,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.545481,1.566157,-0.999215,0.952152,-1.045185,0.151377,-0.058984,-0.556149,-0.676129,0.743111,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,-1.156698,-0.253445,1.726594,0.301274,-0.792412,0.151377,0.483772,1.100858,1.292495,1.370473,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,-1.542723,-1.163245,1.003728,-0.414692,0.878695,-0.895180,-0.466052,0.627428,-1.332337,-1.295816,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [5]:
train_preimputed_df.head()

,Age,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,Sleep_Hours,Screen_Time_Hours,...,Part_Time_Job,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Dropout_Risk
0,17,1,Business,Hostel,68.8,3.2,6.39,1.0,7.6,6.1,...,Yes,Upper-Middle,3.7,8.1,3.9,4.8,5.7,3.3,No,No
1,21,4,Engineering,Day Scholar,50.1,1.9,6.03,1.0,5.4,7.8,...,Yes,Lower-Middle,1.2,7.7,3.9,5.5,1.3,3.9,No,Yes
2,25,4,Law,Hostel,63.8,4.7,5.36,1.0,6.1,4.3,...,No,High,2.7,6.3,3.6,3.1,5.5,NaN,Yes,Yes
3,18,2,Law,Hostel,100.0,3.7,5.72,1.0,6.9,7.8,...,No,Middle,3.5,4.7,4.7,5.2,4.6,7.8,Yes,Yes
4,17,1,Medicine,PG/Rented,90.4,2.6,8.10,0.0,5.5,6.8,...,No,Middle,7.0,3.8,3.3,5.1,5.6,3.4,Yes,No

In [152]:
dt_param_dist = {
    "max_depth": [3, 5, 10, None],
    "min_samples_split": [2, 5, 10],
}
X_train = train_df.drop(columns="Dropout_Risk")
y_train = train_df["Dropout_Risk"]

In [153]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier

dt_search = RandomizedSearchCV(
    estimator=DecisionTreeClassifier(),
    param_distributions=dt_param_dist,
    n_iter=10,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1,
)
dt_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [3, 5, 10, None],
                                        'min_samples_split': [2, 5, 10]},
                   random_state=42, scoring='accuracy')

In [154]:
print(dt_search.best_params_)
print(dt_search.best_score_)

{'min_samples_split': 10, 'max_depth': None}
0.6071428571428571

In [155]:
best_dt = dt_search.best_estimator_
X_valid = valid_df.drop(columns="Dropout_Risk")
y_valid = valid_df["Dropout_Risk"]

print(best_dt.score(X_train, y_train))
print(best_dt.score(X_valid, y_valid))

0.9357142857142857
0.6083333333333333

In [156]:
rf_param_dist = {
    "n_estimators": [10, 20, 50, 100],
    "max_depth": [3, 5, 10, None],
    "min_samples_split": [2, 5, 10],
}

In [157]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

rf_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(),
    param_distributions=rf_param_dist,
    n_iter=10,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1,
)
rf_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [3, 5, 10, None],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [10, 20, 50, 100]},
                   random_state=42, scoring='accuracy')

In [158]:
best_rf = rf_search.best_estimator_
X_valid = valid_df.drop(columns="Dropout_Risk")
y_valid = valid_df["Dropout_Risk"]

print(best_rf.score(X_train, y_train))
print(best_rf.score(X_valid, y_valid))

1.0
0.6666666666666666

In [159]:
print(rf_search.best_params_)

{'n_estimators': 100, 'min_samples_split': 2, 'max_depth': 10}

In [160]:
rf_param_dist_2 = {
    "n_estimators": [10, 20, 50, 100],
    "max_depth": [2, 3, 5, 10],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5, 10],
}

In [161]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

rf_search_2 = RandomizedSearchCV(
    estimator=RandomForestClassifier(),
    param_distributions=rf_param_dist_2,
    n_iter=50,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1,
)
rf_search_2.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=50,
                   n_jobs=-1,
                   param_distributions={'max_depth': [2, 3, 5, 10],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [10, 20, 50, 100]},
                   random_state=42, scoring='accuracy')

In [162]:
best_rf_2 = rf_search_2.best_estimator_
print(best_rf_2.score(X_train, y_train))
print(best_rf_2.score(X_valid, y_valid))

0.8928571428571429
0.6583333333333333

In [163]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from scipy.stats import loguniform

lr_param_dist = {
    "C": loguniform(0.001, 100),
}

lr = LogisticRegression()
lr_search = RandomizedSearchCV(
    lr, 
    lr_param_dist, 
    n_iter=30, 
    cv=5, 
    random_state=42
)
lr_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=30,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x17ce88810>},
                   random_state=42)

In [164]:
best_lr = lr_search.best_estimator_
print(best_lr.score(X_train, y_train))
print(best_lr.score(X_valid, y_valid))

0.7267857142857143
0.675

## สรุป Logistic Regression แบบ Baseline ดีสุดสะงั้น

In [165]:
import joblib

final_model = joblib.load("../models/baseline/lr_raw_model.joblib")
joblib.dump(final_model, "../models/final/lr_final_model.joblib")

['../models/final/lr_final_model.joblib']

### เช็ค Feature Importance เผื่อตัด Feature ทิ้ง

In [168]:
from sklearn.inspection import permutation_importance

result = permutation_importance(final_model, X_valid, y_valid, n_repeats=50, random_state=42)

imp_df = pd.DataFrame({"feature": X_valid.columns, "importance": result.importances_mean})
imp_df = imp_df.sort_values(by="importance", ascending=False)
imp_df

                       feature  importance
2           Attendance_Percent    0.054333
15            Motivation_Score    0.038667
13                Stress_Level    0.037667
3          Study_Hours_Per_Day    0.030833
10       Family_Income_Bracket    0.029833
12        Family_Support_Score    0.025667
7            Screen_Time_Hours    0.023667
16         Peer_Pressure_Score    0.023500
17           Counseling_Access    0.021167
31           Part_Time_Job_Yes    0.019500
29            Part_Time_Job_No    0.018833
11      Financial_Stress_Score    0.018000
5                     Backlogs    0.016500
1                Year_of_Study    0.012667
4                 Previous_GPA    0.011167
6                  Sleep_Hours    0.010333
9        Social_Activity_Score    0.009500
25  Residence_Type_Day Scholar    0.007667
27    Residence_Type_PG/Rented    0.006500
20      Department_Engineering    0.006000
0                          Age    0.004333
8       Exercise_Freq_Per_Week    0.004167
23          Department_Science    0.004000
14               Anxiety_Score    0.002167
26       Residence_Type_Hostel    0.002000
30       Part_Time_Job_Unknown    0.001667
28      Residence_Type_Unknown    0.000333
22         Department_Medicine    0.000000
24          Department_Unknown    0.000000
21              Department_Law    0.000000
19         Department_Business   -0.004000
18             Department_Arts   -0.006500